# -*- coding: utf-8 -*-
"""service_requests/admin.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rl4p8_tdbM5_mfF6q9KdZ1bRaTKlj-C
"""

from django.contrib import admin
from .models import ServiceRequestType, ServiceRequest, RequestAttachment, RequestComment

class RequestAttachmentInline(admin.TabularInline):
    model = RequestAttachment
    extra = 0

class RequestCommentInline(admin.TabularInline):
    model = RequestComment
    extra = 0

class ServiceRequestAdmin(admin.ModelAdmin):
    list_display = ('title', 'request_type', 'customer', 'status', 'created_at', 'updated_at')
    list_filter = ('status', 'request_type', 'created_at')
    search_fields = ('title', 'description', 'customer__username', 'customer__email')
    readonly_fields = ('created_at', 'updated_at')
    inlines = [RequestAttachmentInline, RequestCommentInline]

    fieldsets = (
        ('Request Information', {
            'fields': ('title', 'description', 'request_type', 'status')
        }),
        ('Customer Information', {
            'fields': ('customer',)
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )

class ServiceRequestTypeAdmin(admin.ModelAdmin):
    list_display = ('name', 'description', 'is_active')
    search_fields = ('name', 'description')
    list_filter = ('is_active',)

admin.site.register(ServiceRequestType, ServiceRequestTypeAdmin)
admin.site.register(ServiceRequest, ServiceRequestAdmin)