# -*- coding: utf-8 -*-
"""service_requests/forms.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rl4p8_tdbM5_mfF6q9KdZ1bRaTKlj-C
"""

from django import forms
from .models import ServiceRequest, RequestAttachment, RequestComment

class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['title', 'description', 'request_type']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

class RequestAttachmentForm(forms.ModelForm):
    class Meta:
        model = RequestAttachment
        fields = ['file']

class RequestCommentForm(forms.ModelForm):
    class Meta:
        model = RequestComment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Add a comment...'}),
        }