# -*- coding: utf-8 -*-
"""service_requests/urls.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rl4p8_tdbM5_mfF6q9KdZ1bRaTKlj-C
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.request_list, name='request_list'),
    path('create/', views.create_request, name='create_request'),
    path('<int:request_id>/', views.request_detail, name='request_detail'),
    path('<int:request_id>/add-comment/', views.add_comment, name='add_comment'),
]